### PR TITLE
Add systemd-config tag

### PR DESCRIPTION
**Pull request by jdeanwallace**
Related to [#120](https://github.com/mtlynch/ansible-role-tinypilot/pull/120).

---
This change is [Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37)

### CODE REVIEW

**Review by mtlynch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jdeanwallace)

___
*[tasks/main.yml, line 157 at r1](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37#-MWaahxI1JZNvu8KfPqL:-MWaahxI1JZNvu8KfPqM:b9gqszi) ([raw file](https://github.com/mtlynch/ansible-role-ustreamer/blob/9c7916779dddda2086dc8efc01d5a36e6d6aa1e3/tasks/main.yml#L157)):*
> ```YAML
>     - restart uStreamer
>   tags:
>     - config
> ```

This is actually the only play that needs to run from the convenience script. Can we remove the other tags and rename this to something like `systemd-config`?

**Review by jdeanwallace — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @mtlynch)

___
*[defaults/main.yml, line 14 at r2](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37#-MWfCkjM1CY8idaWErjH:-MWfCkjNDywQwRudfep8:bzhfk1b) ([raw file](https://github.com/mtlynch/ansible-role-ustreamer/blob/75e0ebca5d7b84b3cff8de37809ae1859828717e/defaults/main.yml#L14)):*
> ```YAML
> 
> # Port to listen for connections.
> ustreamer_port: 8001
> ```

I moved these default settings here from the [ustreamer task in the tinypilot ansible role](https://github.com/mtlynch/ansible-role-tinypilot/blob/master/tasks/ustreamer.yml#L5-L11). The problem was that if you run the ustreamer role directly, the default settings for `ustreamer_interface` & `ustreamer_port` broke ustreamer server (i.e. no video in the web UI).

I also moved the `ustreamer_repo` & `ustreamer_repo_version` default values here (seeing as this repo is specifically for tinypilot anyway). This might be a YAGNI thing though :sweat_smile: 
___
*[tasks/main.yml, line 157 at r1](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37#-MWaahxI1JZNvu8KfPqL:-MWfCQUG8MyBonAwBerl:b-896fix) ([raw file](https://github.com/mtlynch/ansible-role-ustreamer/blob/9c7916779dddda2086dc8efc01d5a36e6d6aa1e3/tasks/main.yml#L157)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

This is actually the only play that needs to run from the convenience script. Can we remove the other tags and rename this to something like `systemd-config`?
</blockquote></details>

Done.

**Review by mtlynch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jdeanwallace)

___
*[defaults/main.yml, line 14 at r2](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37#-MWfCkjM1CY8idaWErjH:-MWfFzmJ-BFZAttvl8mT:b-r2x7xt) ([raw file](https://github.com/mtlynch/ansible-role-ustreamer/blob/75e0ebca5d7b84b3cff8de37809ae1859828717e/defaults/main.yml#L14)):*
<details><summary><i>Previously, jdeanwallace (Jason Wallace) wrote…</i></summary><blockquote>

I moved these default settings here from the [ustreamer task in the tinypilot ansible role](https://github.com/mtlynch/ansible-role-tinypilot/blob/master/tasks/ustreamer.yml#L5-L11). The problem was that if you run the ustreamer role directly, the default settings for `ustreamer_interface` & `ustreamer_port` broke ustreamer server (i.e. no video in the web UI).

I also moved the `ustreamer_repo` & `ustreamer_repo_version` default values here (seeing as this repo is specifically for tinypilot anyway). This might be a YAGNI thing though :sweat_smile: 
</blockquote></details>

I think `null` is the more accurate default. The role shouldn't make any assumptions about TinyPilot as the consumer of this role, and `ustreamer` works fine if you launch it with no port or interface params.

ditto for the `ustreamer_repo` settings, since they're assuming TinyPilot is the only client. We should be setting those values at the TinyPilot role level or the `--extra-args` level.
___
*[tasks/main.yml, line 145 at r2](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37#-MWfGJSu26us_TumE4pw:-MWfGJSu26us_TumE4px:b-u9twi3) ([raw file](https://github.com/mtlynch/ansible-role-ustreamer/blob/75e0ebca5d7b84b3cff8de37809ae1859828717e/tasks/main.yml#L145)):*
> ```YAML
>     - restart uStreamer
>   tags:
>     - systemd-config
> ```

Can we reduce the PR to just this change? The other changes are too far out of scope:

https://mtlynch.io/code-review-love/#5-narrowly-scope-changes

**Review by mtlynch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jdeanwallace)

___
*[defaults/main.yml, line 14 at r2](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37#-MWfCkjM1CY8idaWErjH:-MWfWogC44CiTPj-3J9I:b-gbgjtd) ([raw file](https://github.com/mtlynch/ansible-role-ustreamer/blob/75e0ebca5d7b84b3cff8de37809ae1859828717e/defaults/main.yml#L14)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

I think `null` is the more accurate default. The role shouldn't make any assumptions about TinyPilot as the consumer of this role, and `ustreamer` works fine if you launch it with no port or interface params.

ditto for the `ustreamer_repo` settings, since they're assuming TinyPilot is the only client. We should be setting those values at the TinyPilot role level or the `--extra-args` level.
</blockquote></details>

Just to add a bit, I think we need to solve this in `quick-install`. Maybe we should have `quick-install` write the default ustreamer port and interface to `/home/tinypilot/settings.yml` if they're not already set.

Related: https://github.com/mtlynch/tinypilot/issues/622

**Review by jdeanwallace — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mtlynch)

___
*[defaults/main.yml, line 14 at r2](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37#-MWfCkjM1CY8idaWErjH:-MWfStpMC799HreGqgW9:b-jyy43k) ([raw file](https://github.com/mtlynch/ansible-role-ustreamer/blob/75e0ebca5d7b84b3cff8de37809ae1859828717e/defaults/main.yml#L14)):*
> ... and ustreamer works fine if you launch it with no port or interface params.
 
When running only the `systemd-config` tag, it ends up configuring the systemd service with no port or host and I get a 504 error on the frontend for the video stream. [Demo video](https://www.loom.com/share/4fc6f117210b4a4da9e096b71a71635a).
___
*[tasks/main.yml, line 145 at r2](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37#-MWfGJSu26us_TumE4pw:-MWfX0Zb82SVvPAJxVuW:b-896fix) ([raw file](https://github.com/mtlynch/ansible-role-ustreamer/blob/75e0ebca5d7b84b3cff8de37809ae1859828717e/tasks/main.yml#L145)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Can we reduce the PR to just this change? The other changes are too far out of scope:

https://mtlynch.io/code-review-love/#5-narrowly-scope-changes
</blockquote></details>

Done.

**Review by mtlynch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jdeanwallace and @mtlynch)

___
*[defaults/main.yml, line 14 at r2](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37#-MWfCkjM1CY8idaWErjH:-MWfthhU7zhIsY3T0jlg:bufeox9) ([raw file](https://github.com/mtlynch/ansible-role-ustreamer/blob/75e0ebca5d7b84b3cff8de37809ae1859828717e/defaults/main.yml#L14)):*
<details><summary><i>Previously, jdeanwallace (Jason Wallace) wrote…</i></summary><blockquote>

> ... and ustreamer works fine if you launch it with no port or interface params.
 
When running only the `systemd-config` tag, it ends up configuring the systemd service with no port or host and I get a 504 error on the frontend for the video stream. [Demo video](https://www.loom.com/share/4fc6f117210b4a4da9e096b71a71635a).
</blockquote></details>

Right, but that's a tinypilot-level problem. From uStreamer's perspective, everything is working fine. It's listening on 127.0.0.1:8080. TinyPilot's failing because it's looking for video at the wrong port.

We do still need to fix it so that the change video settings script will work properly, but we should avoid baking in TinyPilot-specific assumptions into the ustreamer role.

**Review by mtlynch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jdeanwallace and @mtlynch)

___
*[defaults/main.yml, line 14 at r2](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37#-MWfCkjM1CY8idaWErjH:-MWfuJdu1a1Lc_wkLzPm:b-3e5pdp) ([raw file](https://github.com/mtlynch/ansible-role-ustreamer/blob/75e0ebca5d7b84b3cff8de37809ae1859828717e/defaults/main.yml#L14)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

Right, but that's a tinypilot-level problem. From uStreamer's perspective, everything is working fine. It's listening on 127.0.0.1:8080. TinyPilot's failing because it's looking for video at the wrong port.

We do still need to fix it so that the change video settings script will work properly, but we should avoid baking in TinyPilot-specific assumptions into the ustreamer role.
</blockquote></details>

To clarify, I mean we still need to fix it, but the fix will be in a TinyPilot repo.

**Comment by mtlynch** [comment]
@jdeanwallace - This is ready to merge in, right?

**Review by jdeanwallace — COMMENTED** [review]
Ah, I forgot about this open thread. Yes, this is ready now, thanks to
* https://github.com/mtlynch/tinypilot/pull/624
* https://github.com/mtlynch/ansible-role-tinypilot/pull/120

> *[Reviewable](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37#-:-MXupYw32nvkARpJAX_S:b-o0wdie)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mtlynch)

___
*[defaults/main.yml, line 14 at r2](https://reviewable.io/reviews/mtlynch/ansible-role-ustreamer/37#-MWfCkjM1CY8idaWErjH:-MXuoGqA76KYgneN1zJw:bk4cro8) ([raw file](https://github.com/mtlynch/ansible-role-ustreamer/blob/75e0ebca5d7b84b3cff8de37809ae1859828717e/defaults/main.yml#L14)):*
> ...have quick-install write the default ustreamer port and interface to /home/tinypilot/settings.yml if they're not already set.
>
> Related: mtlynch/tinypilot#622

This has been implemented by https://github.com/mtlynch/tinypilot/pull/624

**Pull request merged**
